### ISSUE TITLE
ab -n 50000 -c 500 -p ./postfile.json -T 'application/json' http://127.0.0.1:/api/

### ISSUE THREAD

**Issue by bsed** [go-playground/validator#286]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:

i ab test v9 ,error
```
fatal error: concurrent map writes

goroutine 49885 [running]:
runtime.throw(0xc314c6, 0x15)
	D:/Go/src/runtime/panic.go:596 +0x9c fp=0xc043468398 sp=0xc043468378
runtime.mapassign(0xb64b80, 0xc04204b2c0, 0xc0434684a8, 0xb98220)
	D:/Go/src/runtime/hashmap.go:499 +0x66e fp=0xc043468438 sp=0xc043468398
zhtj/vendor/gopkg.in/go-playground/validator%2ev9.(*Validate).RegisterStructValidation(0xc0435e79e0, 0xc4dd60, 0xc043468560, 0x1, 0x1)
	E:/gocode/src/zhtj/vendor/gopkg.in/go-playground/validator.v9/validator_instance.go:186 +0x12a fp=0xc0434684e0 sp=0xc043468438
zhtj/validator.GetNation(0xf68340, 0xc04200d030, 0x0, 0x0, 0x0)
	E:/gocode/src/zhtj/validator/national.go:14 +0x17c fp=0xc0434685d0 sp=0xc0434684e0
zhtj/handler.GetNationHandler(0xf68340, 0xc04200d030, 0x0, 0x0)
	E:/gocode/src/zhtj/handler/national.go:51 +0x200 fp=0xc043468dc8 sp=0xc0434685d0
zhtj/vendor/github.com/labstack/echo.(*Echo).add.func1(0xf68340, 0xc04200d030, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/echo.go:463 +0xee fp=0xc043468e38 sp=0xc043468dc8
zhtj/vendor/github.com/labstack/echo/middleware.CORSWithConfig.func1.1(0xf68340, 0xc04200d030, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/middleware/cors.go:113 +0x4b5 fp=0xc043469000 sp=0xc043468e38
zhtj/vendor/github.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0xf68340, 0xc04200d030, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/middleware/recover.go:82 +0x161 fp=0xc043469080 sp=0xc043469000
zhtj/middleware/logger.Logger.func1.1(0xf68340, 0xc04200d030, 0x0, 0x0)
	E:/gocode/src/zhtj/middleware/logger/logger.go:139 +0xb21 fp=0xc0434697f8 sp=0xc043469080
zhtj/vendor/github.com/labstack/echo/middleware.LoggerWithConfig.func2.1(0xf68340, 0xc04200d030, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/middleware/logger.go:111 +0x1af fp=0xc043469930 sp=0xc0434697f8
zhtj/vendor/github.com/labstack/echo/middleware.StaticWithConfig.func1.1(0xf68340, 0xc04200d030, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/middleware/static.go:86 +0x55e fp=0xc043469b60 sp=0xc043469930
zhtj/vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0xf68340, 0xc04200d030, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/echo.go:551 +0x1b7 fp=0xc043469c08 sp=0xc043469b60
zhtj/server.New.func1.1(0xf68340, 0xc04200d030, 0x0, 0x0)
	E:/gocode/src/zhtj/server/server.go:35 +0xc7 fp=0xc043469c68 sp=0xc043469c08
zhtj/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc0421a4ea0, 0xf5dd80, 0xc042857420, 0xc042035400)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/echo.go:560 +0x236 fp=0xc043469d10 sp=0xc043469c68
net/http.serverHandler.ServeHTTP(0xc042092a50, 0xf5dd80, 0xc042857420, 0xc042035400)
	D:/Go/src/net/http/server.go:2568 +0x99 fp=0xc043469d58 sp=0xc043469d10
net/http.(*conn).serve(0xc042e6caa0, 0xf5e800, 0xc0426aa140)
	D:/Go/src/net/http/server.go:1825 +0x619 fp=0xc043469fc8 sp=0xc043469d58
runtime.goexit()
	D:/Go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc043469fd0 sp=0xc043469fc8
created by net/http.(*Server).Serve
	D:/Go/src/net/http/server.go:2668 +0x2d5
```
### Code sample, to showcase or reproduce:

```go
func GetNation(c echo.Context) (*model.NationReqParam, error) {
	validate = validator.New()
	validate.RegisterStructValidation(getNationValidation, model.NationReqParam{})

	u := &model.NationReqParam{}
	if err := c.Bind(u); err != nil {
		return u, err
	}

	return u, validate.Struct(u)
}

```

**Comment by bsed** [comment]
Concurrent read / write lock

**Comment by joeybloggs** [comment]
Hello @bsed 

So it looks like you are creating a new Validator instance, assigning it to a global variable and then Registering a new struct validation each request; the issue is that `RegisterStructValidation` is not thread/goroutine safe as stated in the documentation [here](https://github.com/go-playground/validator/blob/493dfb6209fcb493fcdbc2a0f14b882f2d53979f/validator_instance.go#L178)

By doing it this way you're missing out on all the caching benefits of Validator... so how do you use Validator? there are many ways, but with all Validator is only instantiated once.

1. I see you are using echo and he has a recipe for this library [here](https://echo.labstack.com/guide/request#validate-data)

2. Use a global variable, I know some people frown on this but using it this way gives you a central place to add common validations, and in each custom application still have the ability to Register custom validations for each applications needs; I would even recommend creating a separate package or repo to house this. eg.
```go
package data // in a separate repo

import (
    "gopkg.in/go-playground/validator.v9
)

var Validate = validator.New()

func init(){
    // register any common validation for organization
}
```

and then can use this anywhere, in any application:
```go
import "path-to-data"

data.Validate.Struct(mystruct)

// or

data.Validate.Var(myvar,"required,email")

// and in main.go of project

data.Validate.RegisterStructValidation(...) // these will only be compiled into your project and not the common validations.
```

3. there are more ways like passing through context etc.. but I recommend #2 it works for anyone, with any project and any framework.


Please let me know if this helps :)

**Comment by bsed** [comment]
I've changed it in step two, and the problem still happens. error :
```
fatal error: concurrent map writes

goroutine 18052 [running]:
runtime.throw(0xc2ff86, 0x15)
	D:/Go/src/runtime/panic.go:596 +0x9c fp=0xc043abe398 sp=0xc043abe378
runtime.mapassign(0xb63640, 0xc042c38810, 0xc043abe4a8, 0xb96ce0)
	D:/Go/src/runtime/hashmap.go:499 +0x66e fp=0xc043abe438 sp=0xc043abe398
zhtj/vendor/gopkg.in/go-playground/validator%2ev9.(*Validate).RegisterStructValidation(0xc042039380, 0xc4c820, 0xc043abe560, 0x1, 0x1)
	E:/gocode/src/zhtj/vendor/gopkg.in/go-playground/validator.v9/validator_instance.go:188 +0x12a fp=0xc043abe4e0 sp=0xc043abe438
zhtj/validator.GetNation(0xf66340, 0xc042110af0, 0x0, 0x0, 0x0)
	E:/gocode/src/zhtj/validator/national.go:14 +0x158 fp=0xc043abe5d0 sp=0xc043abe4e0
zhtj/handler.GetNationHandler(0xf66340, 0xc042110af0, 0x0, 0x0)
	E:/gocode/src/zhtj/handler/national.go:51 +0x200 fp=0xc043abedc8 sp=0xc043abe5d0
zhtj/vendor/github.com/labstack/echo.(*Echo).add.func1(0xf66340, 0xc042110af0, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/echo.go:463 +0xee fp=0xc043abee38 sp=0xc043abedc8
zhtj/vendor/github.com/labstack/echo/middleware.CORSWithConfig.func1.1(0xf66340, 0xc042110af0, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/middleware/cors.go:113 +0x4b5 fp=0xc043abf000 sp=0xc043abee38
zhtj/vendor/github.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0xf66340, 0xc042110af0, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/middleware/recover.go:82 +0x161 fp=0xc043abf080 sp=0xc043abf000
zhtj/middleware/logger.Logger.func1.1(0xf66340, 0xc042110af0, 0x0, 0x0)
	E:/gocode/src/zhtj/middleware/logger/logger.go:139 +0xb21 fp=0xc043abf7f8 sp=0xc043abf080
zhtj/vendor/github.com/labstack/echo/middleware.LoggerWithConfig.func2.1(0xf66340, 0xc042110af0, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/middleware/logger.go:111 +0x1af fp=0xc043abf930 sp=0xc043abf7f8
zhtj/vendor/github.com/labstack/echo/middleware.StaticWithConfig.func1.1(0xf66340, 0xc042110af0, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/middleware/static.go:86 +0x55e fp=0xc043abfb60 sp=0xc043abf930
zhtj/vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0xf66340, 0xc042110af0, 0x0, 0x0)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/echo.go:551 +0x1b7 fp=0xc043abfc08 sp=0xc043abfb60
zhtj/server.New.func1.1(0xf66340, 0xc042110af0, 0x0, 0x0)
	E:/gocode/src/zhtj/server/server.go:35 +0xc7 fp=0xc043abfc68 sp=0xc043abfc08
zhtj/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc042036820, 0xf5bd80, 0xc0427cc620, 0xc044079900)
	E:/gocode/src/zhtj/vendor/github.com/labstack/echo/echo.go:560 +0x236 fp=0xc043abfd10 sp=0xc043abfc68
net/http.serverHandler.ServeHTTP(0xc0423ce000, 0xf5bd80, 0xc0427cc620, 0xc044079900)
	D:/Go/src/net/http/server.go:2568 +0x99 fp=0xc043abfd58 sp=0xc043abfd10
net/http.(*conn).serve(0xc0431f3c20, 0xf5c800, 0xc042bdb480)
	D:/Go/src/net/http/server.go:1825 +0x619 fp=0xc043abffc8 sp=0xc043abfd58
runtime.goexit()
	D:/Go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc043abffd0 sp=0xc043abffc8
created by net/http.(*Server).Serve
	D:/Go/src/net/http/server.go:2668 +0x2d5

```

validator.go 
```
package validator

import (
	"gopkg.in/go-playground/validator.v9"
)

var Validate = validator.New()

/*
func init() {

}
*/

```
here `is nation.go` code
```
package validator

import (
	"github.com/labstack/echo"
	"gopkg.in/go-playground/validator.v9"
	"zhtj/model"
	"zhtj/model/std"
	"zhtj/utils"
)


func GetNation(c echo.Context) (*model.NationReqParam, error) {

	Validate.RegisterStructValidation(getNationValidation, model.NationReqParam{})

	// 获取用户注册的信息，进行传入参数校验
	u := &model.NationReqParam{}
	if err := c.Bind(u); err != nil {
		return u, err
	}

	return u, Validate.Struct(u)
}

func getNationValidation(sl validator.StructLevel) {
	input := sl.Current().Interface().(model.NationReqParam)
	if utils.String(input.Lang) == "" || input.Lang == 0 {
		sl.ReportError(input, "Lang", "LANG", std.Msg[std.Code["LANG"]], "")
		return
	}
	if input.Lang != 1 {
		sl.ReportError(input, "Lang", "LANG_FORMAT_ERROR", std.Msg[std.Code["LANG_FORMAT_ERROR"]], "")
		return
	}
}
```

**Comment by bsed** [comment]
i add sync.Mutex in Validate struct 
like this:
```golang
// Validate contains the validator settings and cache
type Validate struct {
	tagName          string
	pool             *sync.Pool
	hasCustomFuncs   bool
	hasTagNameFunc   bool
	tagNameFunc      TagNameFunc
	structLevelFuncs map[reflect.Type]StructLevelFunc
	customFuncs      map[reflect.Type]CustomTypeFunc
	aliases          map[string]string
	validations      map[string]Func
	transTagFunc     map[ut.Translator]map[string]TranslationFunc // map[<locale>]map[<tag>]TranslationFunc
	tagCache         *tagCache
	structCache      *structCache
	processMutex     sync.Mutex
}
```
Step 2 add `v.processMutex.Lock()` and defer `v.processMutex.Unlock()` 
```
func (v *Validate) RegisterStructValidation(fn StructLevelFunc, types ...interface{}) {
	v.processMutex.Lock()
	defer v.processMutex.Unlock()
	if v.structLevelFuncs == nil {

		v.structLevelFuncs = make(map[reflect.Type]StructLevelFunc)
	}

	for _, t := range types {
		v.structLevelFuncs[reflect.TypeOf(t)] = fn

	}

}
```

Step 3  execute the following command
```bash
ab -n 50000 -c 1000 -p ./postfile.json -T 'application/json' http://127.0.0.1:/api/
```

In that case, no error would have occurred

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/27162483-0ca86588-51b4-11e7-9889-a09fe8a2f61b.png)

**Comment by bsed** [comment]
But performance is beginning to decline

**Comment by joeybloggs** [comment]
@bsed I think your misunderstanding when to use `RegisterStructValidation`

your calling `RegisterStructValidation` each http request and that's why you're running into the issue, as it's not thread safe
```go
func GetNation(c echo.Context) (*model.NationReqParam, error) {

	Validate.RegisterStructValidation(getNationValidation, model.NationReqParam{})

	u := &model.NationReqParam{}
	if err := c.Bind(u); err != nil {
		return u, err
	}

	return u, Validate.Struct(u)
}
```

what you should be doing it in main.go or your global validator only once
```go
package validator

import (
	"gopkg.in/go-playground/validator.v9"
)

var Validate = validator.New()

  func init() {
    // register it here or in main.go
    Validate.RegisterStructValidation(getNationValidation, model.NationReqParam{})
  }
}
```

Validator remembers the struct by it's type, and there is no need to register it again.

**Comment by bsed** [comment]
@joeybloggs  thank you，  The problem has been solved and other partners are not expected to encounter such problems, buddy  ^.^
