### ISSUE TITLE
"required_with" associated to "min" does not work with pointers

### ISSUE THREAD

**Issue by samber** [go-playground/validator#589]
### Package version eg. v8, v9: 

v10.2.0

### Issue, Question or Enhancement:

When we validate a pointer to slice with "required_with=field,min=2", the library panics.

Exemple:

```golang
type a struct {
	Field1 []int     `validate:"min=1"`
	Field2 *[]int    `validate:"required_with=field1,min=1"`
}
```

```
panic: Bad field type *[]int

goroutine 1 [running]:
github.com/go-playground/validator/v10.isGte(0x221800, 0x452240, 0x0, 0x44e320)
	/tmp/gopath085574690/pkg/mod/github.com/go-playground/validator/v10@v10.2.0/baked_in.go:1557 +0x980
github.com/go-playground/validator/v10.hasMinOf(0x221800, 0x452240, 0x561701, 0x200f48)
	/tmp/gopath085574690/pkg/mod/github.com/go-playground/validator/v10@v10.2.0/baked_in.go:1642 +0x40
github.com/go-playground/validator/v10.wrapFunc.func1(0x220f00, 0x40e020, 0x221800, 0x452240, 0x221a01, 0x19bac0)
	/tmp/gopath085574690/pkg/mod/github.com/go-playground/validator/v10@v10.2.0/baked_in.go:36 +0x40
github.com/go-playground/validator/v10.(*validate).traverseField(0x452240, 0x220f00, 0x40e020, 0x1b0ae0, 0x40b0b0, 0x99, 0x19bac0, 0x40b0bc, 0x96, 0x55cf00, ...)
	/tmp/gopath085574690/pkg/mod/github.com/go-playground/validator/v10@v10.2.0/validator.go:445 +0x6e0
github.com/go-playground/validator/v10.(*validate).validateStruct(0x452240, 0x220f00, 0x40e020, 0x1b0ae0, 0x40b0b0, 0x99, 0x1b0ae0, 0x40b0b0, 0x99, 0x221a20, ...)
	/tmp/gopath085574690/pkg/mod/github.com/go-playground/validator/v10@v10.2.0/validator.go:77 +0x580
github.com/go-playground/validator/v10.(*Validate).StructCtx(0x43d1d0, 0x220f00, 0x40e020, 0x1b0ae0, 0x40b0b0, 0x8, 0x57019c, 0x9d7)
	/tmp/gopath085574690/pkg/mod/github.com/go-playground/validator/v10@v10.2.0/validator_instance.go:304 +0x360
github.com/go-playground/validator/v10.(*Validate).Struct(...)
	/tmp/gopath085574690/pkg/mod/github.com/go-playground/validator/v10@v10.2.0/validator_instance.go:277
main.main()
	/tmp/sandbox459481103/prog.go:21 +0x160
```
### Code sample, to showcase or reproduce:

https://play.golang.org/p/aR80PqNv1Py

**Comment by deankarn** [comment]
Oh interesting thanks for reporting @samber 
will try to look at this soon, just very very busy

**Comment by deankarn** [comment]
Hey @samber was ablate find some time look this and finally realized there's a type in the validation itself:
`required_with=field1`=>`required_with=Field1` capitol **F** in **Field**

everything appears to work after this change, can you please confirm on your end :)

**Comment by samber** [comment]
![](https://media.giphy.com/media/wMvESGxZ0Cqd2/giphy.gif)

Sorry for wasting your time :-(

We can close...
