### ISSUE TITLE
Panic Bad field type *string, when using required_without and omitempty at the same time

### ISSUE THREAD

**Issue by nigelis** [go-playground/validator#654]
### Package version eg. v8, v9: 

v10.3.0

### Issue, Question, or Enhancement:

When validating a string pointer with `required_without` and `omitempty` at the same time, calling `Struct()` leads to panic.

Using `omitempty` merely is ok. Validating a string instead of a string pointer is ok.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"log"

	"github.com/go-playground/validator/v10"
)

type Sample struct {
	Name string `validate:"omitempty,max=1024"`
	ID   string `validate:"required_without=Name,omitempty,max=64"`
}

type SampleWithPointer struct {
	Name *string `validate:"omitempty,max=1024"`
	ID   *string `validate:"required_without=Name,omitempty,max=64"`
}

func main() {
	name := "name"

	s := &Sample{Name: name}
	swp := &SampleWithPointer{Name: &name}

	validate := validator.New()
	if err := validate.Struct(s); err != nil {
		log.Printf("Validate sample with error, %v", err)
	}
	if err := validate.Struct(swp); err != nil {
		log.Printf("Validate SampeWithPointer with error, %v", err)
	}
}
```

**Comment by nigelis** [comment]
Attach the stack trace.

```
panic: Bad field type *string

goroutine 1 [running]:
github.com/go-playground/validator/v10.isLte(0x11cdf20, 0xc0001245a0, 0xc00029fb00)
        /Users/nigel/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/baked_in.go:1795 +0x63d
github.com/go-playground/validator/v10.hasMaxOf(0x11cdf20, 0xc0001245a0, 0xc0002afc01)
        /Users/nigel/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/baked_in.go:1844 +0x35
github.com/go-playground/validator/v10.wrapFunc.func1(0x11ccee0, 0xc0000160a0, 0x11cdf20, 0xc0001245a0, 0x115a701)
        /Users/nigel/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/baked_in.go:36 +0x39
github.com/go-playground/validator/v10.(*validate).traverseField(0xc0001245a0, 0x11ccee0, 0xc0000160a0, 0x1157940, 0xc000205c30, 0x16, 0x115a7c0, 0xc000205c38, 0x196, 0xc0002ad0c0, ...)
        /Users/nigel/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/validator.go:445 +0x576
github.com/go-playground/validator/v10.(*validate).validateStruct(0xc0001245a0, 0x11ccee0, 0xc0000160a0, 0x1157940, 0xc000205c30, 0x16, 0x11750c0, 0xc000205c30, 0x199, 0x11ceea0, ...)
        /Users/nigel/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/validator.go:77 +0x4d5
github.com/go-playground/validator/v10.(*Validate).StructCtx(0xc00002b380, 0x11ccee0, 0xc0000160a0, 0x1157940, 0xc000205c30, 0x0, 0x0)
        /Users/nigel/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/validator_instance.go:304 +0x380
github.com/go-playground/validator/v10.(*Validate).Struct(...)
        /Users/nigel/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/validator_instance.go:277
main.main()
        ....../main.go:29 +0x18f
exit status 2
```

**Comment by deankarn** [comment]
@nigelis PR #657 merged which fixes this issue, thanks you :)
