### ISSUE TITLE
Custom translation panics if {1} placeholder is before {0}

### ISSUE THREAD

**Issue by popsu** [go-playground/validator#768]
### Package version eg. v9, v10: 
github.com/go-playground/locales v0.13.0
github.com/go-playground/universal-translator v0.17.0
github.com/go-playground/validator/v10 v10.6.0

### Issue, Question or Enhancement:
Custom translator panics if the message has `{1}` placeholder before `{0}`. The same code works if you change the `myMessage` variable from `"hi, error {1} from {0}"` to `"hi, error {0} from {1}"`.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"errors"
	"fmt"
	"reflect"
	"strings"

	"github.com/go-playground/locales/en"
	ut "github.com/go-playground/universal-translator"
	"github.com/go-playground/validator/v10"
)

// use a single instance , it caches struct info
var (
	DefaultEnTranslator ut.Translator
)

const (
	myTag     = "mytag"
	myMessage = "hi, error {1} from {0}"
	// Using the myMessage blow with the numbers {0} and {1} swapped does not panic
	// myMessage = "hi, error {0} from {1}"
)

type User struct {
	Username string
}

func main() {
	v, err := run()

	if err != nil {
		panic(err)
	}

	u := User{
		Username: "invalid name",
	}

	if err := v.Struct(u); err != nil {
		// translate all error at once
		errs := err.(validator.ValidationErrors)

		fmt.Println(errs.Translate(DefaultEnTranslator))

		return
	}

	fmt.Println("All valid")
}

func AddTranslation(v *validator.Validate, tag string, vError string) error {
	registerTag := func(ut ut.Translator) error {
		return ut.Add(tag, vError, false)
	}

	translation := func(ut ut.Translator, fe validator.FieldError) string {
		t, err := ut.T(fe.Tag(), fe.Field(), fe.Param())
		if err != nil {
			return fe.(error).Error()
		}

		return t
	}

	if err := v.RegisterTranslation(tag, DefaultEnTranslator, registerTag, translation); err != nil {
		return err
	}

	return nil
}

func CustomErrorTranslation(v *validator.Validate) error {
	registerName := func(fld reflect.StructField) string {
		name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]
		if name == "-" {
			return ""
		}

		return name
	}

	v.RegisterTagNameFunc(registerName)

	if err := AddTranslation(v, myTag, myMessage); err != nil {
		return err
	}

	return nil
}

func run() (*validator.Validate, error) {
	v := validator.New()

	english := en.New()
	uni := ut.New(english, english)

	var foundTranslator bool
	// initialize the global DefaultEnTranslator
	DefaultEnTranslator, foundTranslator = uni.GetTranslator("en")

	if !foundTranslator {
		return nil, errors.New("error in getting the translator with locale(en)")
	}

	if err := CustomErrorTranslation(v); err != nil {
		return nil, err
	}

	v.RegisterStructValidation(ValidateUserStruct, User{})

	return v, nil
}

func ValidateUserStruct(sl validator.StructLevel) {
	u := sl.Current().Interface().(User)

	if u.Username != "Spongebob" {
		sl.ReportError("field", "fieldname", "structfieldname", myTag, "param")
	}
}

```

Output:
```bash
panic: runtime error: slice bounds out of range [22:10]

goroutine 1 [running]:
github.com/go-playground/universal-translator.(*translator).T(0xc00034dfb0, 0x581500, 0xc00033faa0, 0xc00035d140, 0x2, 0x2, 0xc00034dfb0, 0xc00034dfb0, 0x7f542c3ba401, 0xc00029fe58)
        /home/thovi/go/pkg/mod/github.com/go-playground/universal-translator@v0.17.0/translator.go:310 +0x430
main.AddTranslation.func2(0x5ed628, 0xc00034dfb0, 0x5ecc88, 0xc00014a3f0, 0xc00007f5a8, 0x410401)
        /tmp/tmp.rL6yeOp3Ye/main.go:58 +0x17d
github.com/go-playground/validator/v10.(*fieldError).Translate(0xc00014a3f0, 0x5ed628, 0xc00034dfb0, 0xc00000e210, 0xc0001219e0)
        /home/thovi/go/pkg/mod/github.com/go-playground/validator/v10@v10.6.0/errors.go:274 +0xe2
github.com/go-playground/validator/v10.ValidationErrors.Translate(0xc00033fa90, 0x1, 0x1, 0x5ed628, 0xc00034dfb0, 0x5ea8a0)
        /home/thovi/go/pkg/mod/github.com/go-playground/validator/v10@v10.6.0/errors.go:76 +0xaf
main.main()
        /tmp/tmp.rL6yeOp3Ye/main.go:44 +0x105
exit status 2

```

**Comment by PrakashSuthar** [comment]
This seems to be due to  the implementation in [github.com/go-playground/universal-translator](https://github.com/go-playground/universal-translator) as it looks like currently it supports incremental placeholders only (as per their code). Can be solved via 

1. Creating a custom translator implementing `Translator` interface or 
2. Simply not using non-incremental placeholders in case u want to avoid writing a custom translator
