### ISSUE TITLE
ValidateMap check gtefield panic

### ISSUE THREAD

**Issue by f4haofeng** [go-playground/validator#876]
when i run test case like this，
```go
func TestValidatorMap(t *testing.T) {
	validate := validator.New()
	data := map[string]interface{}{"start": 1, "end": 2}
	rules := map[string]interface{}{"end": "gtefield=start"}

	errs := validate.ValidateMap(data, rules)

	for k, err := range errs {
		fmt.Println(k)
		fmt.Println(err)
	}
}
```
output the message of panic：

panic: Invalid field namespace [recovered]
	panic: Invalid field namespace

goroutine 33 [running]:
testing.tRunner.func1.1(0x59d4040, 0x6037490)
	/Users/zhenghaofeng/go1.5/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000683e00)
	/Users/zhenghaofeng/go1.5/src/testing/testing.go:1075 +0x41a
panic(0x59d4040, 0x6037490)
	/Users/zhenghaofeng/go1.5/src/runtime/panic.go:969 +0x1b9
github.com/go-playground/validator/v10.(*validate).getStructFieldOKInternal(0xc0001338c0, 0x59d33c0, 0x602cbe8, 0x82, 0x5d9e405, 0x5, 0x8, 0x203000, 0x5, 0x203000, ...)
	/Users/zhenghaofeng/go/pkg/mod/github.com/go-playground/validator/v10@v10.10.0/util.go:220 +0x1d35
github.com/go-playground/validator/v10.(*validate).GetStructFieldOK(0xc0001338c0, 0x59d33c0, 0x602cbe8, 0x82, 0x5d835fa, 0xc000351728)
	/Users/zhenghaofeng/go/pkg/mod/github.com/go-playground/validator/v10@v10.10.0/field_level.go:98 +0x69
github.com/go-playground/validator/v10.isGteField(0x60dc5e0, 0xc0001338c0, 0x40104d8)
	/Users/zhenghaofeng/go/pkg/mod/github.com/go-playground/validator/v10@v10.10.0/baked_in.go:1657 +0x89
github.com/go-playground/validator/v10.wrapFunc.func1(0x60b0780, 0xc0001a6008, 0x60dc5e0, 0xc0001338c0, 0x59d33c0)
	/Users/zhenghaofeng/go/pkg/mod/github.com/go-playground/validator/v10@v10.10.0/baked_in.go:40 +0x39
github.com/go-playground/validator/v10.(*validate).traverseField(0xc0001338c0, 0x60b0780, 0xc0001a6008, 0x59d33c0, 0x602cbe8, 0x82, 0x59d33c0, 0x602cbe8, 0x82, 0xc000f1c200, ...)
	/Users/zhenghaofeng/go/pkg/mod/github.com/go-playground/validator/v10@v10.10.0/validator.go:445 +0x5ab
github.com/go-playground/validator/v10.(*Validate).VarCtx(0xc000351b70, 0x60b0780, 0xc0001a6008, 0x59d33c0, 0x602cbe8, 0x5d9e3fc, 0xe, 0x0, 0x0)
	/Users/zhenghaofeng/go/pkg/mod/github.com/go-playground/validator/v10@v10.10.0/validator_instance.go:598 +0x245
github.com/go-playground/validator/v10.Validate.ValidateMapCtx(0x5d92d8d, 0x8, 0xc000846900, 0x0, 0x0, 0x0, 0x0, 0xc0008468a0, 0xc0008468d0, 0x0, ...)
	/Users/zhenghaofeng/go/pkg/mod/github.com/go-playground/validator/v10@v10.10.0/validator_instance.go:163 +0x2ba
github.com/go-playground/validator/v10.(*Validate).ValidateMap(...)
	/Users/zhenghaofeng/go/pkg/mod/github.com/go-playground/validator/v10@v10.10.0/validator_instance.go:174
code.byted.org/pluto/mdd-core/test.TestValidatorMap(0xc000683e00)
	/Users/zhenghaofeng/goProject/Pluto/mdd-core/test/validator_test.go:41 +0x34c
testing.tRunner(0xc000683e00, 0x5e51c18)
	/Users/zhenghaofeng/go1.5/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/Users/zhenghaofeng/go1.5/src/testing/testing.go:1168 +0x2b3

**Comment by zemzale** [comment]
Hey @f4haofeng. The current implementation of `ValidateMap` doesn't support `gtefield` and other cross-field comparisons.

It might be worth looking into, but I don't how feasible it would be.

Please correct me if I am wrong about something @deankarn
